// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Citus.Education.WebApp.Sample.Web.Models;
using Newtonsoft.Json.Linq;

namespace Citus.Education.WebApp.Sample.Web.Models
{
    public static partial class CvCompetenceModelCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<CvCompetenceModel> DeserializeJson(JToken inputObject)
        {
            IList<CvCompetenceModel> deserializedObject = new List<CvCompetenceModel>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                CvCompetenceModel cvCompetenceModel = new CvCompetenceModel();
                cvCompetenceModel.DeserializeJson(iListValue);
                deserializedObject.Add(cvCompetenceModel);
            }
            return deserializedObject;
        }
    }
}
