// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Citus.Education.WebApp.Sample.Web.Models
{
    public partial class CvCompetenceModel
    {
        private string _code;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Code
        {
            get { return this._code; }
            set { this._code = value; }
        }
        
        private string _description;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Description
        {
            get { return this._description; }
            set { this._description = value; }
        }
        
        private int? _groupId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? GroupId
        {
            get { return this._groupId; }
            set { this._groupId = value; }
        }
        
        private int? _id;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Id
        {
            get { return this._id; }
            set { this._id = value; }
        }
        
        private string _name;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set { this._name = value; }
        }
        
        private int? _personId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? PersonId
        {
            get { return this._personId; }
            set { this._personId = value; }
        }
        
        private int? _rateId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? RateId
        {
            get { return this._rateId; }
            set { this._rateId = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the CvCompetenceModel class.
        /// </summary>
        public CvCompetenceModel()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken codeValue = inputObject["Code"];
                if (codeValue != null && codeValue.Type != JTokenType.Null)
                {
                    this.Code = ((string)codeValue);
                }
                JToken descriptionValue = inputObject["Description"];
                if (descriptionValue != null && descriptionValue.Type != JTokenType.Null)
                {
                    this.Description = ((string)descriptionValue);
                }
                JToken groupIdValue = inputObject["GroupId"];
                if (groupIdValue != null && groupIdValue.Type != JTokenType.Null)
                {
                    this.GroupId = ((int)groupIdValue);
                }
                JToken idValue = inputObject["Id"];
                if (idValue != null && idValue.Type != JTokenType.Null)
                {
                    this.Id = ((int)idValue);
                }
                JToken nameValue = inputObject["Name"];
                if (nameValue != null && nameValue.Type != JTokenType.Null)
                {
                    this.Name = ((string)nameValue);
                }
                JToken personIdValue = inputObject["PersonId"];
                if (personIdValue != null && personIdValue.Type != JTokenType.Null)
                {
                    this.PersonId = ((int)personIdValue);
                }
                JToken rateIdValue = inputObject["RateId"];
                if (rateIdValue != null && rateIdValue.Type != JTokenType.Null)
                {
                    this.RateId = ((int)rateIdValue);
                }
            }
        }
    }
}
