//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Citus.Education.WebApp.Sample.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CvCompetence
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int GroupId { get; set; }
        public int RateId { get; set; }
        public int PersonId { get; set; }
    
        public virtual CvCompetencesGroup CvCompetencesGroup { get; set; }
        public virtual CvCompetencesRate CvCompetencesRate { get; set; }
        public virtual Person Person { get; set; }
    }
}
