// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static partial class MVC
{
    public static Citus.Education.WebApp.Sample.Web.Controllers.AccountController Account = new Citus.Education.WebApp.Sample.Web.Controllers.T4MVC_AccountController();
    public static Citus.Education.WebApp.Sample.Web.Controllers.AdminController Admin = new Citus.Education.WebApp.Sample.Web.Controllers.T4MVC_AdminController();
    public static Citus.Education.WebApp.Sample.Web.Controllers.HomeController Home = new Citus.Education.WebApp.Sample.Web.Controllers.T4MVC_HomeController();
    public static Citus.Education.WebApp.Sample.Web.Controllers.ManageController Manage = new Citus.Education.WebApp.Sample.Web.Controllers.T4MVC_ManageController();
    public static T4MVC.SharedController Shared = new T4MVC.SharedController();
}

namespace T4MVC
{
}

namespace T4MVC
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class Dummy
    {
        private Dummy() { }
        public static Dummy Instance = new Dummy();
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_ActionResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_JsonResult : System.Web.Mvc.JsonResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_JsonResult(string area, string controller, string action, string protocol = null): base()
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}
[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal partial class T4MVC_System_Web_Mvc_RedirectResult : System.Web.Mvc.RedirectResult, IT4MVCActionResult
{
    public T4MVC_System_Web_Mvc_RedirectResult(string area, string controller, string action, string protocol = null): base(" ")
    {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links
{
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        private const string URLPATH = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string _references_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/_references.min.js") ? Url("_references.min.js") : Url("_references.js");
        public static readonly string bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.js") ? Url("bootstrap.min.js") : Url("bootstrap.js");
        public static readonly string bootstrap_min_js = Url("bootstrap.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class DataTables {
            private const string URLPATH = "~/Scripts/DataTables";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string autoFill_bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/autoFill.bootstrap.min.js") ? Url("autoFill.bootstrap.min.js") : Url("autoFill.bootstrap.js");
            public static readonly string autoFill_bootstrap_min_js = Url("autoFill.bootstrap.min.js");
            public static readonly string autoFill_foundation_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/autoFill.foundation.min.js") ? Url("autoFill.foundation.min.js") : Url("autoFill.foundation.js");
            public static readonly string autoFill_foundation_min_js = Url("autoFill.foundation.min.js");
            public static readonly string autoFill_jqueryui_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/autoFill.jqueryui.min.js") ? Url("autoFill.jqueryui.min.js") : Url("autoFill.jqueryui.js");
            public static readonly string autoFill_jqueryui_min_js = Url("autoFill.jqueryui.min.js");
            public static readonly string buttons_bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/buttons.bootstrap.min.js") ? Url("buttons.bootstrap.min.js") : Url("buttons.bootstrap.js");
            public static readonly string buttons_bootstrap_min_js = Url("buttons.bootstrap.min.js");
            public static readonly string buttons_colVis_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/buttons.colVis.min.js") ? Url("buttons.colVis.min.js") : Url("buttons.colVis.js");
            public static readonly string buttons_colVis_min_js = Url("buttons.colVis.min.js");
            public static readonly string buttons_flash_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/buttons.flash.min.js") ? Url("buttons.flash.min.js") : Url("buttons.flash.js");
            public static readonly string buttons_flash_min_js = Url("buttons.flash.min.js");
            public static readonly string buttons_foundation_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/buttons.foundation.min.js") ? Url("buttons.foundation.min.js") : Url("buttons.foundation.js");
            public static readonly string buttons_foundation_min_js = Url("buttons.foundation.min.js");
            public static readonly string buttons_html5_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/buttons.html5.min.js") ? Url("buttons.html5.min.js") : Url("buttons.html5.js");
            public static readonly string buttons_html5_min_js = Url("buttons.html5.min.js");
            public static readonly string buttons_jqueryui_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/buttons.jqueryui.min.js") ? Url("buttons.jqueryui.min.js") : Url("buttons.jqueryui.js");
            public static readonly string buttons_jqueryui_min_js = Url("buttons.jqueryui.min.js");
            public static readonly string buttons_print_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/buttons.print.min.js") ? Url("buttons.print.min.js") : Url("buttons.print.js");
            public static readonly string buttons_print_min_js = Url("buttons.print.min.js");
            public static readonly string dataTables_autoFill_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/dataTables.autoFill.min.js") ? Url("dataTables.autoFill.min.js") : Url("dataTables.autoFill.js");
            public static readonly string dataTables_autoFill_min_js = Url("dataTables.autoFill.min.js");
            public static readonly string dataTables_bootstrap_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/dataTables.bootstrap.min.js") ? Url("dataTables.bootstrap.min.js") : Url("dataTables.bootstrap.js");
            public static readonly string dataTables_bootstrap_min_js = Url("dataTables.bootstrap.min.js");
            public static readonly string dataTables_buttons_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/dataTables.buttons.min.js") ? Url("dataTables.buttons.min.js") : Url("dataTables.buttons.js");
            public static readonly string dataTables_buttons_min_js = Url("dataTables.buttons.min.js");
            public static readonly string dataTables_colReorder_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/dataTables.colReorder.min.js") ? Url("dataTables.colReorder.min.js") : Url("dataTables.colReorder.js");
            public static readonly string dataTables_colReorder_min_js = Url("dataTables.colReorder.min.js");
            public static readonly string dataTables_fixedColumns_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/dataTables.fixedColumns.min.js") ? Url("dataTables.fixedColumns.min.js") : Url("dataTables.fixedColumns.js");
            public static readonly string dataTables_fixedColumns_min_js = Url("dataTables.fixedColumns.min.js");
            public static readonly string dataTables_fixedHeader_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/dataTables.fixedHeader.min.js") ? Url("dataTables.fixedHeader.min.js") : Url("dataTables.fixedHeader.js");
            public static readonly string dataTables_fixedHeader_min_js = Url("dataTables.fixedHeader.min.js");
            public static readonly string dataTables_foundation_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/dataTables.foundation.min.js") ? Url("dataTables.foundation.min.js") : Url("dataTables.foundation.js");
            public static readonly string dataTables_foundation_min_js = Url("dataTables.foundation.min.js");
            public static readonly string dataTables_jqueryui_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/dataTables.jqueryui.min.js") ? Url("dataTables.jqueryui.min.js") : Url("dataTables.jqueryui.js");
            public static readonly string dataTables_jqueryui_min_js = Url("dataTables.jqueryui.min.js");
            public static readonly string dataTables_keyTable_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/dataTables.keyTable.min.js") ? Url("dataTables.keyTable.min.js") : Url("dataTables.keyTable.js");
            public static readonly string dataTables_keyTable_min_js = Url("dataTables.keyTable.min.js");
            public static readonly string dataTables_responsive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/dataTables.responsive.min.js") ? Url("dataTables.responsive.min.js") : Url("dataTables.responsive.js");
            public static readonly string dataTables_responsive_min_js = Url("dataTables.responsive.min.js");
            public static readonly string dataTables_rowReorder_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/dataTables.rowReorder.min.js") ? Url("dataTables.rowReorder.min.js") : Url("dataTables.rowReorder.js");
            public static readonly string dataTables_rowReorder_min_js = Url("dataTables.rowReorder.min.js");
            public static readonly string dataTables_scroller_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/dataTables.scroller.min.js") ? Url("dataTables.scroller.min.js") : Url("dataTables.scroller.js");
            public static readonly string dataTables_scroller_min_js = Url("dataTables.scroller.min.js");
            public static readonly string dataTables_select_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/dataTables.select.min.js") ? Url("dataTables.select.min.js") : Url("dataTables.select.js");
            public static readonly string dataTables_select_min_js = Url("dataTables.select.min.js");
            public static readonly string jquery_dataTables_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.dataTables.min.js") ? Url("jquery.dataTables.min.js") : Url("jquery.dataTables.js");
            public static readonly string jquery_dataTables_min_js = Url("jquery.dataTables.min.js");
        }
    
        public static readonly string jquery_1_10_2_intellisense_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.10.2.intellisense.min.js") ? Url("jquery-1.10.2.intellisense.min.js") : Url("jquery-1.10.2.intellisense.js");
        public static readonly string jquery_1_10_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.10.2.min.js") ? Url("jquery-1.10.2.min.js") : Url("jquery-1.10.2.js");
        public static readonly string jquery_1_10_2_min_js = Url("jquery-1.10.2.min.js");
        public static readonly string jquery_1_10_2_min_map = Url("jquery-1.10.2.min.map");
        public static readonly string jquery_validate_vsdoc_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate-vsdoc.min.js") ? Url("jquery.validate-vsdoc.min.js") : Url("jquery.validate-vsdoc.js");
        public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
        public static readonly string jquery_validate_min_js = Url("jquery.validate.min.js");
        public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
        public static readonly string jquery_validate_unobtrusive_min_js = Url("jquery.validate.unobtrusive.min.js");
        public static readonly string modernizr_2_6_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/modernizr-2.6.2.min.js") ? Url("modernizr-2.6.2.min.js") : Url("modernizr-2.6.2.js");
        public static readonly string respond_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/respond.min.js") ? Url("respond.min.js") : Url("respond.js");
        public static readonly string respond_min_js = Url("respond.min.js");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class Views {
            private const string URLPATH = "~/Scripts/Views";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string CvCompetenceList_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/CvCompetenceList.min.js") ? Url("CvCompetenceList.min.js") : Url("CvCompetenceList.js");
        }
    
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        private const string URLPATH = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/bootstrap.min.css") ? Url("bootstrap.min.css") : Url("bootstrap.css");
             
        public static readonly string bootstrap_min_css = Url("bootstrap.min.css");
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class DataTables {
            private const string URLPATH = "~/Content/DataTables";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class css {
                private const string URLPATH = "~/Content/DataTables/css";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string autoFill_bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/autoFill.bootstrap.min.css") ? Url("autoFill.bootstrap.min.css") : Url("autoFill.bootstrap.css");
                     
                public static readonly string autoFill_bootstrap_min_css = Url("autoFill.bootstrap.min.css");
                public static readonly string autoFill_dataTables_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/autoFill.dataTables.min.css") ? Url("autoFill.dataTables.min.css") : Url("autoFill.dataTables.css");
                     
                public static readonly string autoFill_dataTables_min_css = Url("autoFill.dataTables.min.css");
                public static readonly string autoFill_foundation_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/autoFill.foundation.min.css") ? Url("autoFill.foundation.min.css") : Url("autoFill.foundation.css");
                     
                public static readonly string autoFill_foundation_min_css = Url("autoFill.foundation.min.css");
                public static readonly string autoFill_jqueryui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/autoFill.jqueryui.min.css") ? Url("autoFill.jqueryui.min.css") : Url("autoFill.jqueryui.css");
                     
                public static readonly string autoFill_jqueryui_min_css = Url("autoFill.jqueryui.min.css");
                public static readonly string buttons_bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/buttons.bootstrap.min.css") ? Url("buttons.bootstrap.min.css") : Url("buttons.bootstrap.css");
                     
                public static readonly string buttons_bootstrap_min_css = Url("buttons.bootstrap.min.css");
                public static readonly string buttons_dataTables_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/buttons.dataTables.min.css") ? Url("buttons.dataTables.min.css") : Url("buttons.dataTables.css");
                     
                public static readonly string buttons_dataTables_min_css = Url("buttons.dataTables.min.css");
                public static readonly string buttons_foundation_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/buttons.foundation.min.css") ? Url("buttons.foundation.min.css") : Url("buttons.foundation.css");
                     
                public static readonly string buttons_foundation_min_css = Url("buttons.foundation.min.css");
                public static readonly string buttons_jqueryui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/buttons.jqueryui.min.css") ? Url("buttons.jqueryui.min.css") : Url("buttons.jqueryui.css");
                     
                public static readonly string buttons_jqueryui_min_css = Url("buttons.jqueryui.min.css");
                public static readonly string colReorder_bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/colReorder.bootstrap.min.css") ? Url("colReorder.bootstrap.min.css") : Url("colReorder.bootstrap.css");
                     
                public static readonly string colReorder_bootstrap_min_css = Url("colReorder.bootstrap.min.css");
                public static readonly string colReorder_dataTables_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/colReorder.dataTables.min.css") ? Url("colReorder.dataTables.min.css") : Url("colReorder.dataTables.css");
                     
                public static readonly string colReorder_dataTables_min_css = Url("colReorder.dataTables.min.css");
                public static readonly string colReorder_foundation_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/colReorder.foundation.min.css") ? Url("colReorder.foundation.min.css") : Url("colReorder.foundation.css");
                     
                public static readonly string colReorder_foundation_min_css = Url("colReorder.foundation.min.css");
                public static readonly string colReorder_jqueryui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/colReorder.jqueryui.min.css") ? Url("colReorder.jqueryui.min.css") : Url("colReorder.jqueryui.css");
                     
                public static readonly string colReorder_jqueryui_min_css = Url("colReorder.jqueryui.min.css");
                public static readonly string common_scss = Url("common.scss");
                public static readonly string dataTables_bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/dataTables.bootstrap.min.css") ? Url("dataTables.bootstrap.min.css") : Url("dataTables.bootstrap.css");
                     
                public static readonly string dataTables_bootstrap_min_css = Url("dataTables.bootstrap.min.css");
                public static readonly string dataTables_foundation_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/dataTables.foundation.min.css") ? Url("dataTables.foundation.min.css") : Url("dataTables.foundation.css");
                     
                public static readonly string dataTables_foundation_min_css = Url("dataTables.foundation.min.css");
                public static readonly string dataTables_jqueryui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/dataTables.jqueryui.min.css") ? Url("dataTables.jqueryui.min.css") : Url("dataTables.jqueryui.css");
                     
                public static readonly string dataTables_jqueryui_min_css = Url("dataTables.jqueryui.min.css");
                public static readonly string fixedColumns_bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/fixedColumns.bootstrap.min.css") ? Url("fixedColumns.bootstrap.min.css") : Url("fixedColumns.bootstrap.css");
                     
                public static readonly string fixedColumns_bootstrap_min_css = Url("fixedColumns.bootstrap.min.css");
                public static readonly string fixedColumns_dataTables_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/fixedColumns.dataTables.min.css") ? Url("fixedColumns.dataTables.min.css") : Url("fixedColumns.dataTables.css");
                     
                public static readonly string fixedColumns_dataTables_min_css = Url("fixedColumns.dataTables.min.css");
                public static readonly string fixedColumns_foundation_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/fixedColumns.foundation.min.css") ? Url("fixedColumns.foundation.min.css") : Url("fixedColumns.foundation.css");
                     
                public static readonly string fixedColumns_foundation_min_css = Url("fixedColumns.foundation.min.css");
                public static readonly string fixedColumns_jqueryui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/fixedColumns.jqueryui.min.css") ? Url("fixedColumns.jqueryui.min.css") : Url("fixedColumns.jqueryui.css");
                     
                public static readonly string fixedColumns_jqueryui_min_css = Url("fixedColumns.jqueryui.min.css");
                public static readonly string fixedHeader_bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/fixedHeader.bootstrap.min.css") ? Url("fixedHeader.bootstrap.min.css") : Url("fixedHeader.bootstrap.css");
                     
                public static readonly string fixedHeader_bootstrap_min_css = Url("fixedHeader.bootstrap.min.css");
                public static readonly string fixedHeader_dataTables_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/fixedHeader.dataTables.min.css") ? Url("fixedHeader.dataTables.min.css") : Url("fixedHeader.dataTables.css");
                     
                public static readonly string fixedHeader_dataTables_min_css = Url("fixedHeader.dataTables.min.css");
                public static readonly string fixedHeader_foundation_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/fixedHeader.foundation.min.css") ? Url("fixedHeader.foundation.min.css") : Url("fixedHeader.foundation.css");
                     
                public static readonly string fixedHeader_foundation_min_css = Url("fixedHeader.foundation.min.css");
                public static readonly string fixedHeader_jqueryui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/fixedHeader.jqueryui.min.css") ? Url("fixedHeader.jqueryui.min.css") : Url("fixedHeader.jqueryui.css");
                     
                public static readonly string fixedHeader_jqueryui_min_css = Url("fixedHeader.jqueryui.min.css");
                public static readonly string jquery_dataTables_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.dataTables.min.css") ? Url("jquery.dataTables.min.css") : Url("jquery.dataTables.css");
                     
                public static readonly string jquery_dataTables_min_css = Url("jquery.dataTables.min.css");
                public static readonly string jquery_dataTables_themeroller_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.dataTables_themeroller.min.css") ? Url("jquery.dataTables_themeroller.min.css") : Url("jquery.dataTables_themeroller.css");
                     
                public static readonly string keyTable_bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/keyTable.bootstrap.min.css") ? Url("keyTable.bootstrap.min.css") : Url("keyTable.bootstrap.css");
                     
                public static readonly string keyTable_bootstrap_min_css = Url("keyTable.bootstrap.min.css");
                public static readonly string keyTable_dataTables_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/keyTable.dataTables.min.css") ? Url("keyTable.dataTables.min.css") : Url("keyTable.dataTables.css");
                     
                public static readonly string keyTable_dataTables_min_css = Url("keyTable.dataTables.min.css");
                public static readonly string keyTable_foundation_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/keyTable.foundation.min.css") ? Url("keyTable.foundation.min.css") : Url("keyTable.foundation.css");
                     
                public static readonly string keyTable_foundation_min_css = Url("keyTable.foundation.min.css");
                public static readonly string keyTable_jqueryui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/keyTable.jqueryui.min.css") ? Url("keyTable.jqueryui.min.css") : Url("keyTable.jqueryui.css");
                     
                public static readonly string keyTable_jqueryui_min_css = Url("keyTable.jqueryui.min.css");
                public static readonly string mixins_scss = Url("mixins.scss");
                public static readonly string responsive_bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/responsive.bootstrap.min.css") ? Url("responsive.bootstrap.min.css") : Url("responsive.bootstrap.css");
                     
                public static readonly string responsive_bootstrap_min_css = Url("responsive.bootstrap.min.css");
                public static readonly string responsive_dataTables_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/responsive.dataTables.min.css") ? Url("responsive.dataTables.min.css") : Url("responsive.dataTables.css");
                     
                public static readonly string responsive_dataTables_min_css = Url("responsive.dataTables.min.css");
                public static readonly string responsive_foundation_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/responsive.foundation.min.css") ? Url("responsive.foundation.min.css") : Url("responsive.foundation.css");
                     
                public static readonly string responsive_foundation_min_css = Url("responsive.foundation.min.css");
                public static readonly string responsive_jqueryui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/responsive.jqueryui.min.css") ? Url("responsive.jqueryui.min.css") : Url("responsive.jqueryui.css");
                     
                public static readonly string responsive_jqueryui_min_css = Url("responsive.jqueryui.min.css");
                public static readonly string rowReorder_bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/rowReorder.bootstrap.min.css") ? Url("rowReorder.bootstrap.min.css") : Url("rowReorder.bootstrap.css");
                     
                public static readonly string rowReorder_bootstrap_min_css = Url("rowReorder.bootstrap.min.css");
                public static readonly string rowReorder_dataTables_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/rowReorder.dataTables.min.css") ? Url("rowReorder.dataTables.min.css") : Url("rowReorder.dataTables.css");
                     
                public static readonly string rowReorder_dataTables_min_css = Url("rowReorder.dataTables.min.css");
                public static readonly string rowReorder_foundation_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/rowReorder.foundation.min.css") ? Url("rowReorder.foundation.min.css") : Url("rowReorder.foundation.css");
                     
                public static readonly string rowReorder_foundation_min_css = Url("rowReorder.foundation.min.css");
                public static readonly string rowReorder_jqueryui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/rowReorder.jqueryui.min.css") ? Url("rowReorder.jqueryui.min.css") : Url("rowReorder.jqueryui.css");
                     
                public static readonly string rowReorder_jqueryui_min_css = Url("rowReorder.jqueryui.min.css");
                public static readonly string scroller_bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/scroller.bootstrap.min.css") ? Url("scroller.bootstrap.min.css") : Url("scroller.bootstrap.css");
                     
                public static readonly string scroller_bootstrap_min_css = Url("scroller.bootstrap.min.css");
                public static readonly string scroller_dataTables_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/scroller.dataTables.min.css") ? Url("scroller.dataTables.min.css") : Url("scroller.dataTables.css");
                     
                public static readonly string scroller_dataTables_min_css = Url("scroller.dataTables.min.css");
                public static readonly string scroller_foundation_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/scroller.foundation.min.css") ? Url("scroller.foundation.min.css") : Url("scroller.foundation.css");
                     
                public static readonly string scroller_foundation_min_css = Url("scroller.foundation.min.css");
                public static readonly string scroller_jqueryui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/scroller.jqueryui.min.css") ? Url("scroller.jqueryui.min.css") : Url("scroller.jqueryui.css");
                     
                public static readonly string scroller_jqueryui_min_css = Url("scroller.jqueryui.min.css");
                public static readonly string select_bootstrap_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/select.bootstrap.min.css") ? Url("select.bootstrap.min.css") : Url("select.bootstrap.css");
                     
                public static readonly string select_bootstrap_min_css = Url("select.bootstrap.min.css");
                public static readonly string select_dataTables_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/select.dataTables.min.css") ? Url("select.dataTables.min.css") : Url("select.dataTables.css");
                     
                public static readonly string select_dataTables_min_css = Url("select.dataTables.min.css");
                public static readonly string select_foundation_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/select.foundation.min.css") ? Url("select.foundation.min.css") : Url("select.foundation.css");
                     
                public static readonly string select_foundation_min_css = Url("select.foundation.min.css");
                public static readonly string select_jqueryui_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/select.jqueryui.min.css") ? Url("select.jqueryui.min.css") : Url("select.jqueryui.css");
                     
                public static readonly string select_jqueryui_min_css = Url("select.jqueryui.min.css");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class images {
                private const string URLPATH = "~/Content/DataTables/images";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string details_close_png = Url("details_close.png");
                public static readonly string details_open_png = Url("details_open.png");
                public static readonly string sort_asc_png = Url("sort_asc.png");
                public static readonly string sort_asc_disabled_png = Url("sort_asc_disabled.png");
                public static readonly string sort_both_png = Url("sort_both.png");
                public static readonly string sort_desc_png = Url("sort_desc.png");
                public static readonly string sort_desc_disabled_png = Url("sort_desc_disabled.png");
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class swf {
                private const string URLPATH = "~/Content/DataTables/swf";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string flashExport_swf = Url("flashExport.swf");
            }
        
        }
    
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class images {
            private const string URLPATH = "~/Content/images";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            public static readonly string gb_png = Url("gb.png");
            public static readonly string hr_png = Url("hr.png");
        }
    
        public static readonly string Site_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/Site.min.css") ? Url("Site.min.css") : Url("Site.css");
             
    }

    
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class Bundles
    {
        public static partial class Scripts 
        {
            public static partial class DataTables 
            {
                public static class Assets
                {
                    public const string autoFill_bootstrap_js = "~/Scripts/DataTables/autoFill.bootstrap.js"; 
                    public const string autoFill_bootstrap_min_js = "~/Scripts/DataTables/autoFill.bootstrap.min.js"; 
                    public const string autoFill_foundation_js = "~/Scripts/DataTables/autoFill.foundation.js"; 
                    public const string autoFill_foundation_min_js = "~/Scripts/DataTables/autoFill.foundation.min.js"; 
                    public const string autoFill_jqueryui_js = "~/Scripts/DataTables/autoFill.jqueryui.js"; 
                    public const string autoFill_jqueryui_min_js = "~/Scripts/DataTables/autoFill.jqueryui.min.js"; 
                    public const string buttons_bootstrap_js = "~/Scripts/DataTables/buttons.bootstrap.js"; 
                    public const string buttons_bootstrap_min_js = "~/Scripts/DataTables/buttons.bootstrap.min.js"; 
                    public const string buttons_colVis_js = "~/Scripts/DataTables/buttons.colVis.js"; 
                    public const string buttons_colVis_min_js = "~/Scripts/DataTables/buttons.colVis.min.js"; 
                    public const string buttons_flash_js = "~/Scripts/DataTables/buttons.flash.js"; 
                    public const string buttons_flash_min_js = "~/Scripts/DataTables/buttons.flash.min.js"; 
                    public const string buttons_foundation_js = "~/Scripts/DataTables/buttons.foundation.js"; 
                    public const string buttons_foundation_min_js = "~/Scripts/DataTables/buttons.foundation.min.js"; 
                    public const string buttons_html5_js = "~/Scripts/DataTables/buttons.html5.js"; 
                    public const string buttons_html5_min_js = "~/Scripts/DataTables/buttons.html5.min.js"; 
                    public const string buttons_jqueryui_js = "~/Scripts/DataTables/buttons.jqueryui.js"; 
                    public const string buttons_jqueryui_min_js = "~/Scripts/DataTables/buttons.jqueryui.min.js"; 
                    public const string buttons_print_js = "~/Scripts/DataTables/buttons.print.js"; 
                    public const string buttons_print_min_js = "~/Scripts/DataTables/buttons.print.min.js"; 
                    public const string dataTables_autoFill_js = "~/Scripts/DataTables/dataTables.autoFill.js"; 
                    public const string dataTables_autoFill_min_js = "~/Scripts/DataTables/dataTables.autoFill.min.js"; 
                    public const string dataTables_bootstrap_js = "~/Scripts/DataTables/dataTables.bootstrap.js"; 
                    public const string dataTables_bootstrap_min_js = "~/Scripts/DataTables/dataTables.bootstrap.min.js"; 
                    public const string dataTables_buttons_js = "~/Scripts/DataTables/dataTables.buttons.js"; 
                    public const string dataTables_buttons_min_js = "~/Scripts/DataTables/dataTables.buttons.min.js"; 
                    public const string dataTables_colReorder_js = "~/Scripts/DataTables/dataTables.colReorder.js"; 
                    public const string dataTables_colReorder_min_js = "~/Scripts/DataTables/dataTables.colReorder.min.js"; 
                    public const string dataTables_fixedColumns_js = "~/Scripts/DataTables/dataTables.fixedColumns.js"; 
                    public const string dataTables_fixedColumns_min_js = "~/Scripts/DataTables/dataTables.fixedColumns.min.js"; 
                    public const string dataTables_fixedHeader_js = "~/Scripts/DataTables/dataTables.fixedHeader.js"; 
                    public const string dataTables_fixedHeader_min_js = "~/Scripts/DataTables/dataTables.fixedHeader.min.js"; 
                    public const string dataTables_foundation_js = "~/Scripts/DataTables/dataTables.foundation.js"; 
                    public const string dataTables_foundation_min_js = "~/Scripts/DataTables/dataTables.foundation.min.js"; 
                    public const string dataTables_jqueryui_js = "~/Scripts/DataTables/dataTables.jqueryui.js"; 
                    public const string dataTables_jqueryui_min_js = "~/Scripts/DataTables/dataTables.jqueryui.min.js"; 
                    public const string dataTables_keyTable_js = "~/Scripts/DataTables/dataTables.keyTable.js"; 
                    public const string dataTables_keyTable_min_js = "~/Scripts/DataTables/dataTables.keyTable.min.js"; 
                    public const string dataTables_responsive_js = "~/Scripts/DataTables/dataTables.responsive.js"; 
                    public const string dataTables_responsive_min_js = "~/Scripts/DataTables/dataTables.responsive.min.js"; 
                    public const string dataTables_rowReorder_js = "~/Scripts/DataTables/dataTables.rowReorder.js"; 
                    public const string dataTables_rowReorder_min_js = "~/Scripts/DataTables/dataTables.rowReorder.min.js"; 
                    public const string dataTables_scroller_js = "~/Scripts/DataTables/dataTables.scroller.js"; 
                    public const string dataTables_scroller_min_js = "~/Scripts/DataTables/dataTables.scroller.min.js"; 
                    public const string dataTables_select_js = "~/Scripts/DataTables/dataTables.select.js"; 
                    public const string dataTables_select_min_js = "~/Scripts/DataTables/dataTables.select.min.js"; 
                    public const string jquery_dataTables_js = "~/Scripts/DataTables/jquery.dataTables.js"; 
                    public const string jquery_dataTables_min_js = "~/Scripts/DataTables/jquery.dataTables.min.js"; 
                }
            }
            public static partial class Views 
            {
                public static class Assets
                {
                    public const string CvCompetenceList_js = "~/Scripts/Views/CvCompetenceList.js"; 
                }
            }
            public static class Assets
            {
                public const string _references_js = "~/Scripts/_references.js"; 
                public const string bootstrap_js = "~/Scripts/bootstrap.js"; 
                public const string bootstrap_min_js = "~/Scripts/bootstrap.min.js"; 
                public const string jquery_1_10_2_intellisense_js = "~/Scripts/jquery-1.10.2.intellisense.js"; 
                public const string jquery_1_10_2_js = "~/Scripts/jquery-1.10.2.js"; 
                public const string jquery_1_10_2_min_js = "~/Scripts/jquery-1.10.2.min.js"; 
                public const string jquery_validate_js = "~/Scripts/jquery.validate.js"; 
                public const string jquery_validate_min_js = "~/Scripts/jquery.validate.min.js"; 
                public const string jquery_validate_unobtrusive_js = "~/Scripts/jquery.validate.unobtrusive.js"; 
                public const string jquery_validate_unobtrusive_min_js = "~/Scripts/jquery.validate.unobtrusive.min.js"; 
                public const string modernizr_2_6_2_js = "~/Scripts/modernizr-2.6.2.js"; 
                public const string respond_js = "~/Scripts/respond.js"; 
                public const string respond_min_js = "~/Scripts/respond.min.js"; 
            }
        }
        public static partial class Content 
        {
            public static partial class DataTables 
            {
                public static partial class css 
                {
                    public static class Assets
                    {
                        public const string autoFill_bootstrap_css = "~/Content/DataTables/css/autoFill.bootstrap.css";
                        public const string autoFill_bootstrap_min_css = "~/Content/DataTables/css/autoFill.bootstrap.min.css";
                        public const string autoFill_dataTables_css = "~/Content/DataTables/css/autoFill.dataTables.css";
                        public const string autoFill_dataTables_min_css = "~/Content/DataTables/css/autoFill.dataTables.min.css";
                        public const string autoFill_foundation_css = "~/Content/DataTables/css/autoFill.foundation.css";
                        public const string autoFill_foundation_min_css = "~/Content/DataTables/css/autoFill.foundation.min.css";
                        public const string autoFill_jqueryui_css = "~/Content/DataTables/css/autoFill.jqueryui.css";
                        public const string autoFill_jqueryui_min_css = "~/Content/DataTables/css/autoFill.jqueryui.min.css";
                        public const string buttons_bootstrap_css = "~/Content/DataTables/css/buttons.bootstrap.css";
                        public const string buttons_bootstrap_min_css = "~/Content/DataTables/css/buttons.bootstrap.min.css";
                        public const string buttons_dataTables_css = "~/Content/DataTables/css/buttons.dataTables.css";
                        public const string buttons_dataTables_min_css = "~/Content/DataTables/css/buttons.dataTables.min.css";
                        public const string buttons_foundation_css = "~/Content/DataTables/css/buttons.foundation.css";
                        public const string buttons_foundation_min_css = "~/Content/DataTables/css/buttons.foundation.min.css";
                        public const string buttons_jqueryui_css = "~/Content/DataTables/css/buttons.jqueryui.css";
                        public const string buttons_jqueryui_min_css = "~/Content/DataTables/css/buttons.jqueryui.min.css";
                        public const string colReorder_bootstrap_css = "~/Content/DataTables/css/colReorder.bootstrap.css";
                        public const string colReorder_bootstrap_min_css = "~/Content/DataTables/css/colReorder.bootstrap.min.css";
                        public const string colReorder_dataTables_css = "~/Content/DataTables/css/colReorder.dataTables.css";
                        public const string colReorder_dataTables_min_css = "~/Content/DataTables/css/colReorder.dataTables.min.css";
                        public const string colReorder_foundation_css = "~/Content/DataTables/css/colReorder.foundation.css";
                        public const string colReorder_foundation_min_css = "~/Content/DataTables/css/colReorder.foundation.min.css";
                        public const string colReorder_jqueryui_css = "~/Content/DataTables/css/colReorder.jqueryui.css";
                        public const string colReorder_jqueryui_min_css = "~/Content/DataTables/css/colReorder.jqueryui.min.css";
                        public const string dataTables_bootstrap_css = "~/Content/DataTables/css/dataTables.bootstrap.css";
                        public const string dataTables_bootstrap_min_css = "~/Content/DataTables/css/dataTables.bootstrap.min.css";
                        public const string dataTables_foundation_css = "~/Content/DataTables/css/dataTables.foundation.css";
                        public const string dataTables_foundation_min_css = "~/Content/DataTables/css/dataTables.foundation.min.css";
                        public const string dataTables_jqueryui_css = "~/Content/DataTables/css/dataTables.jqueryui.css";
                        public const string dataTables_jqueryui_min_css = "~/Content/DataTables/css/dataTables.jqueryui.min.css";
                        public const string fixedColumns_bootstrap_css = "~/Content/DataTables/css/fixedColumns.bootstrap.css";
                        public const string fixedColumns_bootstrap_min_css = "~/Content/DataTables/css/fixedColumns.bootstrap.min.css";
                        public const string fixedColumns_dataTables_css = "~/Content/DataTables/css/fixedColumns.dataTables.css";
                        public const string fixedColumns_dataTables_min_css = "~/Content/DataTables/css/fixedColumns.dataTables.min.css";
                        public const string fixedColumns_foundation_css = "~/Content/DataTables/css/fixedColumns.foundation.css";
                        public const string fixedColumns_foundation_min_css = "~/Content/DataTables/css/fixedColumns.foundation.min.css";
                        public const string fixedColumns_jqueryui_css = "~/Content/DataTables/css/fixedColumns.jqueryui.css";
                        public const string fixedColumns_jqueryui_min_css = "~/Content/DataTables/css/fixedColumns.jqueryui.min.css";
                        public const string fixedHeader_bootstrap_css = "~/Content/DataTables/css/fixedHeader.bootstrap.css";
                        public const string fixedHeader_bootstrap_min_css = "~/Content/DataTables/css/fixedHeader.bootstrap.min.css";
                        public const string fixedHeader_dataTables_css = "~/Content/DataTables/css/fixedHeader.dataTables.css";
                        public const string fixedHeader_dataTables_min_css = "~/Content/DataTables/css/fixedHeader.dataTables.min.css";
                        public const string fixedHeader_foundation_css = "~/Content/DataTables/css/fixedHeader.foundation.css";
                        public const string fixedHeader_foundation_min_css = "~/Content/DataTables/css/fixedHeader.foundation.min.css";
                        public const string fixedHeader_jqueryui_css = "~/Content/DataTables/css/fixedHeader.jqueryui.css";
                        public const string fixedHeader_jqueryui_min_css = "~/Content/DataTables/css/fixedHeader.jqueryui.min.css";
                        public const string jquery_dataTables_css = "~/Content/DataTables/css/jquery.dataTables.css";
                        public const string jquery_dataTables_min_css = "~/Content/DataTables/css/jquery.dataTables.min.css";
                        public const string jquery_dataTables_themeroller_css = "~/Content/DataTables/css/jquery.dataTables_themeroller.css";
                        public const string keyTable_bootstrap_css = "~/Content/DataTables/css/keyTable.bootstrap.css";
                        public const string keyTable_bootstrap_min_css = "~/Content/DataTables/css/keyTable.bootstrap.min.css";
                        public const string keyTable_dataTables_css = "~/Content/DataTables/css/keyTable.dataTables.css";
                        public const string keyTable_dataTables_min_css = "~/Content/DataTables/css/keyTable.dataTables.min.css";
                        public const string keyTable_foundation_css = "~/Content/DataTables/css/keyTable.foundation.css";
                        public const string keyTable_foundation_min_css = "~/Content/DataTables/css/keyTable.foundation.min.css";
                        public const string keyTable_jqueryui_css = "~/Content/DataTables/css/keyTable.jqueryui.css";
                        public const string keyTable_jqueryui_min_css = "~/Content/DataTables/css/keyTable.jqueryui.min.css";
                        public const string responsive_bootstrap_css = "~/Content/DataTables/css/responsive.bootstrap.css";
                        public const string responsive_bootstrap_min_css = "~/Content/DataTables/css/responsive.bootstrap.min.css";
                        public const string responsive_dataTables_css = "~/Content/DataTables/css/responsive.dataTables.css";
                        public const string responsive_dataTables_min_css = "~/Content/DataTables/css/responsive.dataTables.min.css";
                        public const string responsive_foundation_css = "~/Content/DataTables/css/responsive.foundation.css";
                        public const string responsive_foundation_min_css = "~/Content/DataTables/css/responsive.foundation.min.css";
                        public const string responsive_jqueryui_css = "~/Content/DataTables/css/responsive.jqueryui.css";
                        public const string responsive_jqueryui_min_css = "~/Content/DataTables/css/responsive.jqueryui.min.css";
                        public const string rowReorder_bootstrap_css = "~/Content/DataTables/css/rowReorder.bootstrap.css";
                        public const string rowReorder_bootstrap_min_css = "~/Content/DataTables/css/rowReorder.bootstrap.min.css";
                        public const string rowReorder_dataTables_css = "~/Content/DataTables/css/rowReorder.dataTables.css";
                        public const string rowReorder_dataTables_min_css = "~/Content/DataTables/css/rowReorder.dataTables.min.css";
                        public const string rowReorder_foundation_css = "~/Content/DataTables/css/rowReorder.foundation.css";
                        public const string rowReorder_foundation_min_css = "~/Content/DataTables/css/rowReorder.foundation.min.css";
                        public const string rowReorder_jqueryui_css = "~/Content/DataTables/css/rowReorder.jqueryui.css";
                        public const string rowReorder_jqueryui_min_css = "~/Content/DataTables/css/rowReorder.jqueryui.min.css";
                        public const string scroller_bootstrap_css = "~/Content/DataTables/css/scroller.bootstrap.css";
                        public const string scroller_bootstrap_min_css = "~/Content/DataTables/css/scroller.bootstrap.min.css";
                        public const string scroller_dataTables_css = "~/Content/DataTables/css/scroller.dataTables.css";
                        public const string scroller_dataTables_min_css = "~/Content/DataTables/css/scroller.dataTables.min.css";
                        public const string scroller_foundation_css = "~/Content/DataTables/css/scroller.foundation.css";
                        public const string scroller_foundation_min_css = "~/Content/DataTables/css/scroller.foundation.min.css";
                        public const string scroller_jqueryui_css = "~/Content/DataTables/css/scroller.jqueryui.css";
                        public const string scroller_jqueryui_min_css = "~/Content/DataTables/css/scroller.jqueryui.min.css";
                        public const string select_bootstrap_css = "~/Content/DataTables/css/select.bootstrap.css";
                        public const string select_bootstrap_min_css = "~/Content/DataTables/css/select.bootstrap.min.css";
                        public const string select_dataTables_css = "~/Content/DataTables/css/select.dataTables.css";
                        public const string select_dataTables_min_css = "~/Content/DataTables/css/select.dataTables.min.css";
                        public const string select_foundation_css = "~/Content/DataTables/css/select.foundation.css";
                        public const string select_foundation_min_css = "~/Content/DataTables/css/select.foundation.min.css";
                        public const string select_jqueryui_css = "~/Content/DataTables/css/select.jqueryui.css";
                        public const string select_jqueryui_min_css = "~/Content/DataTables/css/select.jqueryui.min.css";
                    }
                }
                public static partial class images 
                {
                    public static class Assets
                    {
                    }
                }
                public static partial class swf 
                {
                    public static class Assets
                    {
                    }
                }
                public static class Assets
                {
                }
            }
            public static partial class images 
            {
                public static class Assets
                {
                }
            }
            public static class Assets
            {
                public const string bootstrap_css = "~/Content/bootstrap.css";
                public const string bootstrap_min_css = "~/Content/bootstrap.min.css";
                public const string Site_css = "~/Content/Site.css";
            }
        }
    }
}

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
internal static class T4MVCHelpers {
    // You can change the ProcessVirtualPath method to modify the path that gets returned to the client.
    // e.g. you can prepend a domain, or append a query string:
    //      return "http://localhost" + path + "?foo=bar";
    private static string ProcessVirtualPathDefault(string virtualPath) {
        // The path that comes in starts with ~/ and must first be made absolute
        string path = VirtualPathUtility.ToAbsolute(virtualPath);
        
        // Add your own modifications here before returning the path
        return path;
    }

    // Calling ProcessVirtualPath through delegate to allow it to be replaced for unit testing
    public static Func<string, string> ProcessVirtualPath = ProcessVirtualPathDefault;

    // Calling T4Extension.TimestampString through delegate to allow it to be replaced for unit testing and other purposes
    public static Func<string, string> TimestampString = System.Web.Mvc.T4Extensions.TimestampString;

    // Logic to determine if the app is running in production or dev environment
    public static bool IsProduction() { 
        return (HttpContext.Current != null && !HttpContext.Current.IsDebuggingEnabled); 
    }
}





#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114


