// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Citus.Education.WebApp.Sample.Web.WebAPIClient.Models;
using Newtonsoft.Json.Linq;

namespace Citus.Education.WebApp.Sample.Web.WebAPIClient.Models
{
    public static partial class ExternalLoginViewModelCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<ExternalLoginViewModel> DeserializeJson(JToken inputObject)
        {
            IList<ExternalLoginViewModel> deserializedObject = new List<ExternalLoginViewModel>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                ExternalLoginViewModel externalLoginViewModel = new ExternalLoginViewModel();
                externalLoginViewModel.DeserializeJson(iListValue);
                deserializedObject.Add(externalLoginViewModel);
            }
            return deserializedObject;
        }
    }
}
