// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Citus.Education.WebApp.Sample.Web.WebAPIClient.Models;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace Citus.Education.WebApp.Sample.Web.WebAPIClient.Models
{
    public partial class ManageInfoViewModel
    {
        private string _email;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Email
        {
            get { return this._email; }
            set { this._email = value; }
        }
        
        private IList<ExternalLoginViewModel> _externalLoginProviders;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<ExternalLoginViewModel> ExternalLoginProviders
        {
            get { return this._externalLoginProviders; }
            set { this._externalLoginProviders = value; }
        }
        
        private string _localLoginProvider;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string LocalLoginProvider
        {
            get { return this._localLoginProvider; }
            set { this._localLoginProvider = value; }
        }
        
        private IList<UserLoginInfoViewModel> _logins;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<UserLoginInfoViewModel> Logins
        {
            get { return this._logins; }
            set { this._logins = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ManageInfoViewModel class.
        /// </summary>
        public ManageInfoViewModel()
        {
            this.ExternalLoginProviders = new LazyList<ExternalLoginViewModel>();
            this.Logins = new LazyList<UserLoginInfoViewModel>();
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken emailValue = inputObject["Email"];
                if (emailValue != null && emailValue.Type != JTokenType.Null)
                {
                    this.Email = ((string)emailValue);
                }
                JToken externalLoginProvidersSequence = ((JToken)inputObject["ExternalLoginProviders"]);
                if (externalLoginProvidersSequence != null && externalLoginProvidersSequence.Type != JTokenType.Null)
                {
                    foreach (JToken externalLoginProvidersValue in ((JArray)externalLoginProvidersSequence))
                    {
                        ExternalLoginViewModel externalLoginViewModel = new ExternalLoginViewModel();
                        externalLoginViewModel.DeserializeJson(externalLoginProvidersValue);
                        this.ExternalLoginProviders.Add(externalLoginViewModel);
                    }
                }
                JToken localLoginProviderValue = inputObject["LocalLoginProvider"];
                if (localLoginProviderValue != null && localLoginProviderValue.Type != JTokenType.Null)
                {
                    this.LocalLoginProvider = ((string)localLoginProviderValue);
                }
                JToken loginsSequence = ((JToken)inputObject["Logins"]);
                if (loginsSequence != null && loginsSequence.Type != JTokenType.Null)
                {
                    foreach (JToken loginsValue in ((JArray)loginsSequence))
                    {
                        UserLoginInfoViewModel userLoginInfoViewModel = new UserLoginInfoViewModel();
                        userLoginInfoViewModel.DeserializeJson(loginsValue);
                        this.Logins.Add(userLoginInfoViewModel);
                    }
                }
            }
        }
    }
}
