// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Citus.Education.WebApp.Sample.Web;
using Microsoft.Rest;

namespace Citus.Education.WebApp.Sample.Web
{
    public partial interface ICitusEducationWebAppSampleWebAPI : IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        Uri BaseUri
        {
            get; set; 
        }
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        ServiceClientCredentials Credentials
        {
            get; set; 
        }
        
        IAccount Account
        {
            get; 
        }
        
        ICV CV
        {
            get; 
        }
        
        IValues Values
        {
            get; 
        }
    }
}
